# Generated by Django 4.2.3 on 2023-08-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorrecaoMonetaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('multa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('valor_corrigido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
