# Generated by Django 4.2.3 on 2023-07-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta',
            field=models.CharField(choices=[('DA', 'DAYANE'), ('PO', 'POLYANA'), ('CN', 'CONTA'), ('ME', 'MEI'), ('CX', 'CAIXA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(choices=[('ME', 'MENSALIDADE'), ('AL', 'ALUGUEL'), ('CO', 'COPASA'), ('MA', 'MATERIAL'), ('FU', 'FUNCIONARIOS'), ('CP', 'COMPRA_EQUIPAMENTOS'), ('RE', 'REFORMAS_MELHORIAS'), ('PR', 'PRODUTOS_LIMPEZA'), ('OU', 'OUTRAS_DESPESAS'), ('OT', 'OUTRAS_RECEITAS'), ('DI', 'DISTRIBUICAO_LUCROS'), ('RS', 'RESERVA_CAIXA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='forma_pagamento',
            field=models.CharField(choices=[('DN', 'DINHEIRO'), ('CC', 'CARTAO_CREDITO'), ('CB', 'CONTA_BANCARIA'), ('RC', 'RESERVA_CAIXA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('RE', 'RECEITA'), ('DE', 'DESPESA'), ('RE', 'RESERVA'), ('RE', 'DISTRIBUICAO'), ('RE', 'TRANSFERENCIA')], max_length=50),
        ),
    ]
