# Generated by Django 4.2.3 on 2023-07-06 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('alergia', models.CharField(blank=True, max_length=200)),
                ('responsavel_1', models.CharField(max_length=100)),
                ('telefone_1', models.CharField(blank=True, max_length=20)),
                ('cpf_1', models.CharField(blank=True, max_length=20)),
                ('rg_1', models.CharField(blank=True, max_length=20)),
                ('responsavel_2', models.CharField(max_length=100)),
                ('telefone_2', models.CharField(blank=True, max_length=20)),
                ('cpf_2', models.CharField(blank=True, max_length=20)),
                ('rg_2', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('modalidade', models.CharField(choices=[('INTEGRAL', 'INTEGRAL'), ('PARCIAL_MANHA', 'PARCIAL_MANHA'), ('PARCIAL_TARDE', 'PARCIAL_TARDE'), ('PERSOLIZADO', 'PERSOLIZADO')], max_length=50)),
                ('autorizados_a_buscar', models.CharField(blank=True, max_length=200)),
                ('inicio_contrato', models.DateField()),
                ('fim_contrato', models.DateField(blank=True)),
                ('situacao', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transações'},
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='referencia',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta',
            field=models.CharField(choices=[('DAYANE', 'DAYANE'), ('POLYANA', 'POLYANA'), ('CONTA', 'CONTA'), ('MEI', 'MEI'), ('CAIXA', 'CAIXA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(choices=[('MENSALIDADE', 'MENSALIDADE'), ('ALUGUEL', 'ALUGUEL'), ('COPASA', 'COPASA'), ('MATERIAL', 'MATERIAL'), ('FUNCIONARIOS', 'FUNCIONARIOS'), ('COMPRA_EQUIPAMENTOS', 'COMPRA_EQUIPAMENTOS'), ('REFORMAS_MELHORIAS', 'REFORMAS_MELHORIAS'), ('PRODUTOS_LIMPEZA', 'PRODUTOS_LIMPEZA'), ('OUTRAS_DESPESAS', 'OUTRAS_DESPESAS'), ('OUTRAS_RECEITAS', 'OUTRAS_RECEITAS'), ('DISTRIBUICAO_LUCROS', 'DISTRIBUICAO_LUCROS'), ('RESERVA_CAIXA', 'RESERVA_CAIXA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'DINHEIRO'), ('CARTAO_CREDITO', 'CARTAO_CREDITO'), ('CONTA_BANCARIA', 'CONTA_BANCARIA'), ('RESERVA_CAIXA', 'RESERVA_CAIXA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'RECEITA'), ('DESPESA', 'DESPESA'), ('RESERVA', 'RESERVA'), ('DISTRIBUICAO', 'DISTRIBUICAO'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=50),
        ),
        migrations.AddField(
            model_name='transacao',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.aluno'),
        ),
    ]
