# Generated by Django 4.2.3 on 2023-07-06 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_transacao_options_alter_transacao_conta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
