# Generated by Django 4.2.3 on 2023-07-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_aluno_alergia_alter_aluno_autorizados_a_buscar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='conta',
            field=models.CharField(choices=[('DAYANE', 'DAYANE'), ('POLYANA', 'POLYANA'), ('RESERVA', 'RESERVA'), ('MEI', 'MEI'), ('CAIXA', 'CAIXA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'DINHEIRO'), ('CONTA_BANCARIA', 'CONTA_BANCARIA'), ('RESERVA_CAIXA', 'RESERVA_CAIXA')], max_length=100),
        ),
    ]
