# Generated by Django 4.2.3 on 2023-07-06 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_transacao_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.aluno'),
        ),
    ]
