# Generated by Django 4.2.3 on 2023-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_transacao_conta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(choices=[('MENSALIDADE', 'MENSALIDADE'), ('ALUGUEL', 'ALUGUEL'), ('COPASA', 'COPASA'), ('MATERIAL', 'MATERIAL'), ('FUNCIONARIOS', 'FUNCIONARIOS'), ('COMPRA_EQUIPAMENTOS', 'COMPRA_EQUIPAMENTOS'), ('REFORMAS_MELHORIAS', 'REFORMAS_MELHORIAS'), ('PRODUTOS_LIMPEZA', 'PRODUTOS_LIMPEZA'), ('OUTRAS_DESPESAS', 'OUTRAS_DESPESAS'), ('OUTRAS_RECEITAS', 'OUTRAS_RECEITAS'), ('DISTRIBUICAO_LUCROS', 'DISTRIBUICAO_LUCROS'), ('RESERVA_CAIXA', 'RESERVA_CAIXA'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=50),
        ),
    ]
