# Generated by Django 4.2.3 on 2023-07-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_transacao_conta_alter_transacao_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='referencia',
        ),
    ]
